#  Data Preprocessing

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv")

In [4]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [6]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df = df.drop_duplicates()

In [9]:
print(df.columns)
df.columns = df.columns.str.strip()

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [10]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

In [11]:
df

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [12]:
df.to_csv(r"D:\Apollo_AgriVerse\02_Datasets\Interim\Crop\crop_clean.csv", index=False)

In [13]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [19]:
import pandas as pd

# Existing dataset
df1 = pd.read_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv")



print(df.shape)

(2200, 8)

In [20]:
import pandas as pd

# Load existing dataset
df = pd.read_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv")

# New crop data
new_crops = pd.DataFrame({
    "N": [110, 95, 120],
    "P": [45, 50, 60],
    "K": [55, 65, 70],
    "temperature": [29.5, 24.8, 31.2],
    "humidity": [78, 82, 70],
    "ph": [6.8, 6.5, 7.0],
    "rainfall": [180, 140, 220],
    "label": ["sugarcane", "potato", "onion"]
})

# Add new rows
df = pd.concat([df, new_crops], ignore_index=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Save back to the same file
df.to_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv", index=False)

print("New crops added successfully!")
print(df["label"].unique())

New crops added successfully!
['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee' 'sugarcane' 'potato' 'onion']

In [21]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv")

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Remove extra spaces
df.columns = df.columns.str.strip()
df["label"] = df["label"].str.strip().str.lower()

# Check missing values
print(df.isnull().sum())

# Fill missing numeric values
numeric_cols = ["N","P","K","temperature","humidity","ph","rainfall"]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Save cleaned dataset
df.to_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv", index=False)

print("Cleaning completed.")
print(df["label"].value_counts())

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64
Cleaning completed.
label
rice           100
maize          100
coffee         100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
sugarcane        1
potato           1
onion            1
Name: count, dtype: int64

In [24]:
# ==========================================
# Apollo AgriVerse - Crop Dataset Expansion
# ==========================================

import pandas as pd
import numpy as np

# -----------------------------
# Load Original Dataset
# -----------------------------
df = pd.read_csv(r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv")

print("Original Dataset Shape:", df.shape)

# -----------------------------
# Clean Existing Dataset
# -----------------------------
df.columns = df.columns.str.strip().str.lower()

df["label"] = (
    df["label"]
    .astype(str)
    .str.strip()
    .str.lower()
)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Fill missing values
numeric_cols = ["n","p","k","temperature","humidity","ph","rainfall"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    df[col] = df[col].fillna(df[col].median())

# -----------------------------
# New Crops to Add
# -----------------------------
new_crops = [
    "sugarcane",
    "potato",
    "onion",
    "tomato",
    "cabbage",
    "cauliflower",
    "brinjal",
    "okra",
    "garlic",
    "ginger",
    "turmeric",
    "soybean",
    "groundnut",
    "mustard",
    "sunflower",
    "wheat",
    "barley",
    "bajra",
    "jowar",
    "ragi",
    "pea",
    "capsicum",
    "cucumber",
    "pumpkin",
    "spinach",
    "fenugreek",
    "coriander",
    "chilli"
]

# -----------------------------
# Generate New Samples
# -----------------------------
generated_rows = []

samples_per_crop = 100

for crop in new_crops:

    for i in range(samples_per_crop):

        row = {

            "n": np.random.randint(20,140),

            "p": np.random.randint(15,90),

            "k": np.random.randint(15,120),

            "temperature": round(np.random.uniform(18,38),2),

            "humidity": round(np.random.uniform(45,95),2),

            "ph": round(np.random.uniform(5.5,7.8),2),

            "rainfall": round(np.random.uniform(40,350),2),

            "label": crop

        }

        generated_rows.append(row)

new_df = pd.DataFrame(generated_rows)

print("Generated Samples:", new_df.shape)

# -----------------------------
# Merge Datasets
# -----------------------------
final_df = pd.concat([df,new_df],ignore_index=True)

# -----------------------------
# Final Cleaning
# -----------------------------
final_df.drop_duplicates(inplace=True)

final_df["temperature"] = final_df["temperature"].clip(10,50)
final_df["humidity"] = final_df["humidity"].clip(20,100)
final_df["ph"] = final_df["ph"].clip(3,9)
final_df["rainfall"] = final_df["rainfall"].clip(0,500)

# -----------------------------
# Shuffle Dataset
# -----------------------------
final_df = final_df.sample(frac=1,random_state=42).reset_index(drop=True)

# -----------------------------
# Save Dataset
# -----------------------------
save_path = r"D:\Apollo_AgriVerse\02_Datasets\Raw\Crop\Crop_recommendation.csv"

final_df.to_csv(save_path,index=False)

print("\nDataset Saved Successfully")

print("\nFinal Shape:",final_df.shape)

print("\nTotal Crops:",final_df["label"].nunique())

print("\nCrop Names:\n")

print(sorted(final_df["label"].unique()))

print("\nCrop Count:\n")

print(final_df["label"].value_counts())

Original Dataset Shape: (2203, 8)
Generated Samples: (2800, 8)

Dataset Saved Successfully

Final Shape: (5003, 8)

Total Crops: 50

Crop Names:

['apple', 'bajra', 'banana', 'barley', 'blackgram', 'brinjal', 'cabbage', 'capsicum', 'cauliflower', 'chickpea', 'chilli', 'coconut', 'coffee', 'coriander', 'cotton', 'cucumber', 'fenugreek', 'garlic', 'ginger', 'grapes', 'groundnut', 'jowar', 'jute', 'kidneybeans', 'lentil', 'maize', 'mango', 'mothbeans', 'mungbean', 'muskmelon', 'mustard', 'okra', 'onion', 'orange', 'papaya', 'pea', 'pigeonpeas', 'pomegranate', 'potato', 'pumpkin', 'ragi', 'rice', 'soybean', 'spinach', 'sugarcane', 'sunflower', 'tomato', 'turmeric', 'watermelon', 'wheat']

Crop Count:

label
onion          101
potato         101
sugarcane      101
pigeonpeas     100
coffee         100
lentil         100
rice           100
grapes         100
apple          100
spinach        100
ragi           100
mustard        100
sunflower      100
groundnut      100
fenugreek      100
soybean        100
garlic         100
bajra          100
cauliflower    100
cabbage        100
muskmelon      100
watermelon     100
barley         100
okra           100
coriander      100
jowar          100
wheat          100
coconut        100
cucumber       100
mungbean       100
banana         100
pumpkin        100
maize          100
papaya         100
blackgram      100
orange         100
chickpea       100
pea            100
jute           100
tomato         100
brinjal        100
pomegranate    100
kidneybeans    100
mango          100
chilli         100
turmeric       100
mothbeans      100
capsicum       100
ginger         100
cotton         100
Name: count, dtype: int64

In [25]:
df.to_csv(r"D:\Apollo_AgriVerse\02_Datasets\Interim\Crop\crop_clean.csv", index=False)